<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PalabraSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('palabras')->insert([

            // ========== CATEGORÍA 1: SALUDOS (20 palabras) ==========
            ['categoria_id' => 1, 'palabra_quechua' => 'Rimaykullayki', 'palabra_espanol' => 'Hola', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Rayku', 'palabra_espanol' => 'Gracias', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Imaynallam', 'palabra_espanol' => '¿Cómo estás?', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Allin p\'unchay', 'palabra_espanol' => 'Buenos días', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Allin tuta', 'palabra_espanol' => 'Buenas noches', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Tupananchikkama', 'palabra_espanol' => 'Adiós', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Ama hina', 'palabra_espanol' => 'De nada', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Waleku', 'palabra_espanol' => 'Bien', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 1, 'palabra_quechua' => 'Manan allinchu', 'palabra_espanol' => 'Mal', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Sumaqlla', 'palabra_espanol' => 'Muy bien', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Q\'aya kama', 'palabra_espanol' => 'Hasta mañana', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Minchakama', 'palabra_espanol' => 'Hasta luego', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Kusisqa tuparinaykikama', 'palabra_espanol' => 'Feliz de verte', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 1, 'palabra_quechua' => 'Imamanta?', 'palabra_espanol' => '¿De qué?', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Mayqen?', 'palabra_espanol' => '¿Cuál?', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Ima sutiyki?', 'palabra_espanol' => '¿Cómo te llamas?', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Sutiyqa...', 'palabra_espanol' => 'Me llamo...', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Maymantam kanki?', 'palabra_espanol' => '¿De dónde eres?', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Allinllachu?', 'palabra_espanol' => '¿Todo bien?', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 1, 'palabra_quechua' => 'Kusikuni tuparusqaykita', 'palabra_espanol' => 'Me alegra conocerte', 'nivel_dificultad' => 3, 'puntos' => 20],

            // ========== CATEGORÍA 2: ANIMALES (20 palabras) ==========
            ['categoria_id' => 2, 'palabra_quechua' => 'Allqu', 'palabra_espanol' => 'Perro', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Michi', 'palabra_espanol' => 'Gato', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Llama', 'palabra_espanol' => 'Llama', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Puma', 'palabra_espanol' => 'Puma', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 2, 'palabra_quechua' => 'Atuq', 'palabra_espanol' => 'Zorro', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 2, 'palabra_quechua' => 'Kuntur', 'palabra_espanol' => 'Cóndor', 'nivel_dificultad' => 2, 'puntos' => 20],
            ['categoria_id' => 2, 'palabra_quechua' => 'Wanaku', 'palabra_espanol' => 'Guanaco', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 2, 'palabra_quechua' => 'Ukumari', 'palabra_espanol' => 'Oso', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 2, 'palabra_quechua' => 'Wallpa', 'palabra_espanol' => 'Gallina', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Wisk\'acha', 'palabra_espanol' => 'Vizcacha', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 2, 'palabra_quechua' => 'Taruka', 'palabra_espanol' => 'Venado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 2, 'palabra_quechua' => 'Achuqalla', 'palabra_espanol' => 'Comadreja', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 2, 'palabra_quechua' => 'Khuchi', 'palabra_espanol' => 'Chancho', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Waca', 'palabra_espanol' => 'Vaca', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Kawallu', 'palabra_espanol' => 'Caballo', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Uwiha', 'palabra_espanol' => 'Oveja', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'K\'uchi', 'palabra_espanol' => 'Cuy', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 2, 'palabra_quechua' => 'Waqu', 'palabra_espanol' => 'Zorrino', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 2, 'palabra_quechua' => 'Ch\'iwi', 'palabra_espanol' => 'Pájaro', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 2, 'palabra_quechua' => 'Mach\'aqway', 'palabra_espanol' => 'Serpiente', 'nivel_dificultad' => 2, 'puntos' => 15],

            // ========== CATEGORÍA 3: PARTES DEL CUERPO (20 palabras) ==========
            ['categoria_id' => 3, 'palabra_quechua' => 'Uma', 'palabra_espanol' => 'Cabeza', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Mak\'illa', 'palabra_espanol' => 'Mano', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Ñawi', 'palabra_espanol' => 'Ojo', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Rinri', 'palabra_espanol' => 'Oreja', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Sinqa', 'palabra_espanol' => 'Nariz', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Simi', 'palabra_espanol' => 'Boca', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Kunka', 'palabra_espanol' => 'Cuello', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Qhicha', 'palabra_espanol' => 'Espalda', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Wasa', 'palabra_espanol' => 'Cintura', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Rodilla', 'palabra_espanol' => 'Rodilla', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Chaki', 'palabra_espanol' => 'Pie', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 3, 'palabra_quechua' => 'Siki', 'palabra_espanol' => 'Trasero', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Wiqri', 'palabra_espanol' => 'Estómago', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Sunqu', 'palabra_espanol' => 'Corazón', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Qallu', 'palabra_espanol' => 'Lengua', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Kiru', 'palabra_espanol' => 'Diente', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Uqhu', 'palabra_espanol' => 'Pulmón', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 3, 'palabra_quechua' => 'K\'ara', 'palabra_espanol' => 'Piel', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Tullu', 'palabra_espanol' => 'Hueso', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 3, 'palabra_quechua' => 'Sillu', 'palabra_espanol' => 'Uña', 'nivel_dificultad' => 2, 'puntos' => 15],

            // ========== CATEGORÍA 4: COLORES (20 palabras) ==========
            ['categoria_id' => 4, 'palabra_quechua' => 'Yuraq', 'palabra_espanol' => 'Blanco', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Yana', 'palabra_espanol' => 'Negro', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Puka', 'palabra_espanol' => 'Rojo', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Q\'omer', 'palabra_espanol' => 'Verde', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Anqas', 'palabra_espanol' => 'Azul', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Q\'ellu', 'palabra_espanol' => 'Amarillo', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Kulli', 'palabra_espanol' => 'Morado', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Ch\'umpi', 'palabra_espanol' => 'Marrón', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Uqi', 'palabra_espanol' => 'Gris', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 4, 'palabra_quechua' => 'Ñañu', 'palabra_espanol' => 'Rosa', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'K\'ello', 'palabra_espanol' => 'Naranja', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Ch\'illka', 'palabra_espanol' => 'Verde claro', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Q\'iwi', 'palabra_espanol' => 'Azul marino', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Puka puka', 'palabra_espanol' => 'Rosado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Quri q\'ellu', 'palabra_espanol' => 'Dorado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Khilihili', 'palabra_espanol' => 'Amarillo claro', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Pukapuka', 'palabra_espanol' => 'Carmesí', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 4, 'palabra_quechua' => 'Ch\'umchu', 'palabra_espanol' => 'Plateado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Wayanay', 'palabra_espanol' => 'Verde oscuro', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 4, 'palabra_quechua' => 'Yana q\'ellu', 'palabra_espanol' => 'Mostaza', 'nivel_dificultad' => 2, 'puntos' => 15],

            // ========== CATEGORÍA 5: EMOCIONES (20 palabras) ==========
            ['categoria_id' => 5, 'palabra_quechua' => 'Kusisqa', 'palabra_espanol' => 'Feliz', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 5, 'palabra_quechua' => 'Llakisqa', 'palabra_espanol' => 'Triste', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 5, 'palabra_quechua' => 'Phiñasqa', 'palabra_espanol' => 'Enojado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Manchachisqa', 'palabra_espanol' => 'Asustado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Kuyakuq', 'palabra_espanol' => 'Enamorado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Samincha', 'palabra_espanol' => 'Tranquilo', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Tukuyta yuyay', 'palabra_espanol' => 'Preocupado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Maypin', 'palabra_espanol' => 'Confundido', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 5, 'palabra_quechua' => 'Aymuray', 'palabra_espanol' => 'Sorprendido', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Ima kay', 'palabra_espanol' => 'Preocupación', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Sayk\'usqa', 'palabra_espanol' => 'Cansado', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Chirisqa', 'palabra_espanol' => 'Tranquilidad', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'T\'ikarisqa', 'palabra_espanol' => 'Floreciendo (alegre)', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 5, 'palabra_quechua' => 'Muchu', 'palabra_espanol' => 'Desesperado', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 5, 'palabra_quechua' => 'Yawar phiña', 'palabra_espanol' => 'Furia', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 5, 'palabra_quechua' => 'Ch\'ulla', 'palabra_espanol' => 'Soledad', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Munay', 'palabra_espanol' => 'Querer / Amar', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'P\'itiy', 'palabra_espanol' => 'Abrumado', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 5, 'palabra_quechua' => 'Samiy', 'palabra_espanol' => 'Descanso', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 5, 'palabra_quechua' => 'Kusiy', 'palabra_espanol' => 'Alegría', 'nivel_dificultad' => 1, 'puntos' => 10],

            // ========== CATEGORÍA 6: EXPRESIONES (20 palabras) ==========
            ['categoria_id' => 6, 'palabra_quechua' => 'Alinchu', 'palabra_espanol' => '¿Está bien?', 'nivel_dificultad' => 1, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Sumaq', 'palabra_espanol' => 'Hermoso', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 6, 'palabra_quechua' => 'Arí', 'palabra_espanol' => 'Sí', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 6, 'palabra_quechua' => 'Manam', 'palabra_espanol' => 'No', 'nivel_dificultad' => 1, 'puntos' => 10],
            ['categoria_id' => 6, 'palabra_quechua' => 'Allillanmi', 'palabra_espanol' => 'Todo bien', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Maypin?', 'palabra_espanol' => '¿Dónde está?', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Imataq kay?', 'palabra_espanol' => '¿Qué es esto?', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Ama sua', 'palabra_espanol' => 'No robes', 'nivel_dificultad' => 3, 'puntos' => 25],
            ['categoria_id' => 6, 'palabra_quechua' => 'Urpichallay', 'palabra_espanol' => 'Ay mi palomita', 'nivel_dificultad' => 3, 'puntos' => 25],
            ['categoria_id' => 6, 'palabra_quechua' => 'Ama qilla', 'palabra_espanol' => 'No seas flojo', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 6, 'palabra_quechua' => 'Ama llulla', 'palabra_espanol' => 'No seas mentiroso', 'nivel_dificultad' => 3, 'puntos' => 20],
            ['categoria_id' => 6, 'palabra_quechua' => 'Allichu', 'palabra_espanol' => 'Por favor', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Dispinsuyu', 'palabra_espanol' => 'Disculpe / Permiso', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Kusisqalla', 'palabra_espanol' => 'Con gusto', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Manam atiymanchu', 'palabra_espanol' => 'No puedo', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Atiymanmi', 'palabra_espanol' => 'Puedo', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Yanapaway', 'palabra_espanol' => 'Ayúdame', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Uyariway', 'palabra_espanol' => 'Escúchame', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Qaway', 'palabra_espanol' => 'Mira', 'nivel_dificultad' => 2, 'puntos' => 15],
            ['categoria_id' => 6, 'palabra_quechua' => 'Hamuy', 'palabra_espanol' => 'Ven', 'nivel_dificultad' => 2, 'puntos' => 15],
        ]);
    }
}